config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :create]
  # Defines the root path route ("/")
  # root "articles#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @restaurant = Restaurant.new
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def inde
    @review = Review.where(restaurant_id)
  end


  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review.params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurants)
  end

  def update
  @review = Review.find(params[:id])
  @review.update(params[:review])
  end

  private

  def set restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Créer un nouveau restaurant</h1>

<%= render 'index', restaurant: @restaurant %>

<%= link_to 'Retour à la liste des restaurants', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Liste des restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <div class="restaurant">
    <h2><%= restaurant.name %></h2>
    <p><%= restaurant.phone_number %></p>
    <p><%= restaurant.address %></p>
    <p><%= restaurant.category %></p>
    <p><%= link_to "Voir les détails", restaurant_path(restaurant) %></p>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "index", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <%= review.content %>
    </li>
  <% end %>
</ul>
<br>

<div>

app/views/reviews/create.html.erb
<h1>Ajouter une nouvelle critique</h1>

<%= render 'index', review: @review %>

<%= link_to 'Retour au restaurant', restaurant_path(@restaurant) %>

app/views/reviews/form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, placeholder: "Write your review here" %>
  <%= f.input :rating, placeholder: "Add a rating (1-5)" %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Add your review below:</h1>
<%= render 'form', restaurant: @restaurant, review: @review %>

<br>
<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>